apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  namespace: roboshop
spec:
# list of containers
  containers:
  - name: hello-pod
    image: nginx    # it is pulling from docker hub
    ports:
    - containerPort: 80

